// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayAutoConnectionDialog", "", "main_frame");
            akit.PushButton("Apply_button", "diaAutoConnection");
            akit.PushButton("Cancel_button", "diaAutoConnection");
        }
    }
}
