// Generated by Tekla.Technology.Akit.ScriptBuilder
using System;
using System.Drawing;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Globalization;
using System.Diagnostics;
using System.Windows.Forms;
using System.Xml;

using Tekla.Structures;
using Tekla.Structures.Model;
using Tekla.Structures.Model.Operations;
using TSMUI = Tekla.Structures.Model.UI;
using Tekla.Technology.Akit.UserScript;
using Tekla.Technology.Scripting;

[assembly: Tekla.Technology.Scripting.Compiler.ReferenceAttribute("Tekla.Application.Library")]
[assembly: Tekla.Technology.Scripting.Compiler.ReferenceAttribute("Tekla.Structures.Datatype")]
[assembly: Tekla.Technology.Scripting.Compiler.Reference(@"%XSBIN%\plugins\Interop.Excel.dll")]
[assembly: Tekla.Technology.Scripting.Compiler.Reference("System.Xml")]


namespace Tekla.Technology.Akit.UserScript
{
	public class Script
	{
		public static void Run(Tekla.Technology.Akit.IScript akit)
		{
			//
			TestSearch.GetPartsByMark();
		}
	}
	
	public static class TestSearch 
	{
		
	}
}
