// Generated by Tekla.Technology.Akit.ScriptBuilder

using Tekla.Structures.Model;
using Tekla.Structures;
using System.Windows.Forms;
using System.IO;
using System.Diagnostics;

namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            string ApplicationName = "DirectoryBrowser.exe";
            string xsbin = "";
            Model CurrentModel = new Model();
            TeklaStructuresSettings.GetAdvancedOption("XSBIN", ref xsbin);           
            string EnginePath = xsbin + "\\applications\\Tekla\\Tools\\" + ApplicationName;

            Process NewProcess = new Process();

            if (File.Exists(EnginePath))
            {
                NewProcess.StartInfo.FileName = EnginePath;

                try
                {
                    NewProcess.Start();
                }
                catch
                {
                    MessageBox.Show("Starting " + ApplicationName + " failed.");
                }
            }
            else
            {
                MessageBox.Show(ApplicationName + " not found.");
            }
        }
    }
}