// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
            akit.Callback("acmd_rotate_view", "Z-15.0", "main_frame");
        }
    }
}
