// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayOptionSettingsDialog", "", "main_frame");
            akit.ListSelect("dia_option_settings", "listCategory", "Units and decimals");
        }
    }
}
