// Generated by Tekla.Technology.Akit.ScriptBuilder

namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdDisplayFramesAndFoldmarksCB", "", "main_frame");
            akit.ValueChange("dia_drframe_dialog", "x1", "0.000000000000");
            akit.ValueChange("dia_drframe_dialog", "y1", "0.000000000000");
            akit.ValueChange("dia_drframe_dialog", "x2", "0.000000000000");
            akit.ValueChange("dia_drframe_dialog", "y2", "0.000000000000");
            akit.ValueChange("dia_drframe_dialog", "drframe1_en", "0");
            akit.ValueChange("dia_drframe_dialog", "drframe1_en", "1");
            akit.ValueChange("dia_drframe_dialog", "drframe2_en", "1");
            akit.ValueChange("dia_drframe_dialog", "drframe2_en", "0");
            akit.ValueChange("dia_drframe_dialog", "pen", "152");
            akit.ValueChange("dia_drframe_dialog", "pen", "162");
            akit.ValueChange("dia_drframe_dialog", "pen_2", "152");
            akit.ValueChange("dia_drframe_dialog", "x1", "0.1953125");
            akit.ValueChange("dia_drframe_dialog", "y1", "0.1953125");
            akit.ValueChange("dia_drframe_dialog", "x2", "0.1953125");
            akit.ValueChange("dia_drframe_dialog", "y2", "0.1953125");
            akit.PushButton("drframe_apply", "dia_drframe_dialog");
            akit.PushButton("drframe_ok", "dia_drframe_dialog");
        }
    }
}
