// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {			
			akit.Callback("acmd_display_dialog", "dia_view_dialog", "main_frame");
            akit.PushButton("v1_show", "dia_view_dialog");
            akit.PushButton("on_off_button", "Modelling view setup");
            akit.PushButton("on_off_button", "Modelling view setup");
            akit.ValueChange("Modelling view setup", "sd_joint_symbols", "1");
            akit.ValueChange("Modelling view setup", "sd_joint_joint_symbols", "1");
            akit.PushButton("sd_modify", "Modelling view setup");
            akit.PushButton("sd_ok", "Modelling view setup");
            akit.PushButton("v1_cancel", "dia_view_dialog");
			
        }
    }
}
