// Generated by Tekla.Technology.Akit.ScriptBuilder



namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmd_change_workfloor", "", "main_frame");
            akit.PushButton("wf1_change", "Work floor");
            akit.PushButton("wf1_cancel", "Work floor");
        }
    }
}
