// Generated by Tekla.Technology.Akit.ScriptBuilder

namespace Tekla.Technology.Akit.UserScript
{
    public class Script
    {
        public static void Run(Tekla.Technology.Akit.IScript akit)
        {
            akit.Callback("acmdZoomToSelected", "", "main_frame");
        }
    }
}